apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: cluster-tooling
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
  source:
    chart: gitea
    repoURL: https://dl.gitea.io/charts
    targetRevision: 10.4.1
    helm:
      releaseName: gitea
      values: |
        redis-cluster:
          enabled: false
        redis:
          enabled: false
        postgresql:
          enabled: false
        postgresql-ha:
          enabled: false

        persistence:
          enabled: false

        gitea:
          config:
            database:
              DB_TYPE: sqlite3
            session:
              PROVIDER: memory
            cache:
              ADAPTER: memory
            queue:
              TYPE: level
