
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-tooling
  source:
    repoURL: http://gitea:30000/gitea/gitops-lab.git
    targetRevision: main
    path: gitops-code/argocd-manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
